[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.zhangyk.space", custom_domain = true },
  { pattern = "quay.zhangyk.space", custom_domain = true },
  { pattern = "gcr.zhangyk.space", custom_domain = true },
  { pattern = "k8s-gcr.zhangyk.space", custom_domain = true },
  { pattern = "k8s.zhangyk.space", custom_domain = true },
  { pattern = "ghcr.zhangyk.space", custom_domain = true },
  { pattern = "cloudsmith.zhangyk.space", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.zhangyk.space", custom_domain = true }
